services:
  - type: web
    name: your-backend-api
    env: python
    plan: free
    buildCommand: ""
    startCommand: uvicorn main:app --host=0.0.0.0 --port=10000
    envVars:
      - key: OPENAI_API_KEY
        value: your_openai_key
      - key: GROQ_API_KEY
        value: your_groq_key
